version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app/scraping
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: dist/scripts/start.sh
      timeout: 300
      runas: ec2-user