version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/scraper
    overwrite: true
permissions:
  - object: /var/www/scraper
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: installDependenciesScraping.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stopScraping.sh
      timeout: 300
      runas: ec2-user
      environment:
        variables:
          NODE_PID: "14709"
  ApplicationStart:
    - location: startScraping.sh
      timeout: 1200
      runas: ec2-user