version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build
      - cd dist
      - node index.js

artifacts:
  files:
    - '**/*'