version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build
      - cp -r /path/to/compiled/files/* /var/www/scraper/
  post_build:
    commands:
      - cd dist
      - node index.js
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: ./dist